import React, { useState, useMemo } from "react";
import { PRAnalysis, PRInfo, AzureDevOpsParams } from "../types.ts";

interface AnalysisDisplayProps {
  analysis: PRAnalysis;
  prInfo: PRInfo;
  params: AzureDevOpsParams;
  processedCount: number;
  totalCount: number;
  isAnalyzing: boolean;
  onLoadNext: () => void;
}

const SeverityBadge: React.FC<{ severity: string }> = ({ severity }) => {
  const colors = {
    low: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    medium: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    high: "bg-rose-500/10 text-rose-400 border-rose-500/20",
  };
  const colorKey = severity.toLowerCase() as keyof typeof colors;
  const colorClass = colors[colorKey] || colors.low;
  return (
    <span
      className={`px-1.5 py-0.5 rounded text-[9px] font-bold border uppercase tracking-widest ${colorClass}`}
    >
      {severity}
    </span>
  );
};

const KPICard: React.FC<{
  label: string;
  value: string | number;
  subtext?: string;
  color?: string;
  icon?: string;
}> = ({ label, value, subtext, color = "text-white", icon }) => (
  <div className="bg-[#111113] border border-white/5 rounded-xl p-4 flex flex-col justify-between">
    <div className="flex justify-between items-start mb-2">
      <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">
        {label}
      </span>
      {icon && <i className={`fas ${icon} text-[10px] text-slate-600`}></i>}
    </div>
    <div className={`text-xl font-black tracking-tight ${color}`}>{value}</div>
    {subtext && (
      <div className="text-[9px] text-slate-600 font-bold uppercase mt-1">
        {subtext}
      </div>
    )}
  </div>
);

const TypeBadge: React.FC<{ type: string }> = ({ type }) => {
  const icons = {
    logic: "fa-microchip",
    security: "fa-shield-halved",
    style: "fa-paint-brush",
    performance: "fa-bolt",
    contract: "fa-file-signature",
  };
  const icon = icons[type as keyof typeof icons] || "fa-info-circle";
  const colors = type === "contract" ? "text-violet-400" : "text-slate-500";
  return (
    <span
      className={`text-[10px] font-bold ${colors} uppercase tracking-widest flex items-center gap-1`}
    >
      <i className={`fas ${icon} text-[9px]`}></i> {type}
    </span>
  );
};

export const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({
  analysis,
  prInfo,
  params,
  processedCount,
  totalCount,
  isAnalyzing,
  onLoadNext,
}) => {
  const [severityFilter, setSeverityFilter] = useState<
    "all" | "high" | "medium" | "low"
  >("all");

  const isComplete = processedCount === totalCount;
  const stats = analysis.stats ?? {
    complexityScore: 0,
    riskLevel: "Medium",
    estimatedReviewMinutes: 0,
    blastRadius: "Module-wide",
    testPresence: "Missing",
    breakingChange: false,
  };
  const healthColors = {
    Excellent: "text-emerald-400",
    Good: "text-blue-400",
    "Needs Improvement": "text-amber-400",
    Critical: "text-rose-400",
  };

  const riskColors = {
    Low: "text-emerald-400",
    Medium: "text-amber-400",
    High: "text-rose-400",
    Critical: "text-rose-600",
  };

  const progress = Math.round((processedCount / totalCount) * 100);

  const copyToADO = () => {
    if (!isComplete) return;
    const markdown = `
# 🤖 PR Management Intelligence
**Overall Health:** ${analysis.overallHealth} | **Risk Level:** ${
      stats.riskLevel || "Unknown"
    }

## 📊 Management KPIs
- **Complexity Score:** ${stats.complexityScore || 0}/10
- **Blast Radius:** ${stats.blastRadius || "Unknown"}
- **Tests:** ${stats.testPresence || "Unknown"}
- **Est. Review Time:** ${stats.estimatedReviewMinutes || 0} mins
- **Breaking Change:** ${stats.breakingChange ? "⚠️ YES" : "✅ No"}

## 🏗️ Architectural Impact
${analysis.architecturalImpact}

## ⛓️ System Alignment
${analysis.contextAlignment || "Standard alignment confirmed."}

---
*Generated by PR Genius Internal Audit Tool*
    `.trim();
    navigator.clipboard.writeText(markdown);
    alert("Markdown summary copied to clipboard!");
  };

  const filteredComments = useMemo(() => {
    const comments = analysis.codeReviewComments || [];
    if (severityFilter === "all") return comments;
    return comments.filter((c) => c.severity.toLowerCase() === severityFilter);
  }, [analysis.codeReviewComments, severityFilter]);

  const counts = useMemo(() => {
    const comments = analysis.codeReviewComments || [];
    return {
      all: comments.length,
      high: comments.filter((c) => c.severity.toLowerCase() === "high").length,
      medium: comments.filter((c) => c.severity.toLowerCase() === "medium")
        .length,
      low: comments.filter((c) => c.severity.toLowerCase() === "low").length,
    };
  }, [analysis.codeReviewComments]);

  const getADOLink = (filePath: string, line?: number) => {
    const cleanPath = filePath.startsWith("/") ? filePath : `/${filePath}`;
    const baseUrl = `https://dev.azure.com/${params.organization}/${params.project}/_git/${params.repository}/pullrequest/${params.pullRequestId}`;
    const query = `?_a=files&path=${encodeURIComponent(cleanPath)}`;
    const lineAnchor = line
      ? `&line=${line}&lineStartColumn=1&lineEndColumn=1&lineStyle=plain`
      : "";
    return `${baseUrl}${query}${lineAnchor}`;
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {/* Boss Dashboard Header */}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
        <KPICard
          label="Health"
          value={analysis.overallHealth}
          color={healthColors[analysis.overallHealth]}
          icon="fa-heartbeat"
        />
        <KPICard
          label="Risk"
          value={stats.riskLevel || "Unknown"}
          color={
            riskColors[stats.riskLevel as keyof typeof riskColors] ||
            riskColors.Medium
          }
          icon="fa-biohazard"
        />
        <KPICard
          label="Complexity"
          value={`${stats.complexityScore || 0}/10`}
          subtext="Maintainability"
          icon="fa-brain"
        />
        <KPICard
          label="Scope"
          value={stats.blastRadius || "Unknown"}
          subtext="Impact Area"
          icon="fa-expand-arrows-alt"
        />
        <KPICard
          label="Effort"
          value={`${stats.estimatedReviewMinutes || 0}m`}
          subtext="Est. Review"
          icon="fa-clock"
        />
        <KPICard
          label="Tests"
          value={stats.testPresence || "Unknown"}
          color={
            stats.testPresence === "Missing"
              ? "text-rose-400"
              : "text-emerald-400"
          }
          icon="fa-vial"
        />
      </div>

      {/* Action Banner */}
      <div className="flex justify-between items-center bg-[#111113] border border-white/5 rounded-xl px-6 py-4 shadow-sm">
        <div className="flex items-center gap-4">
          {stats.breakingChange && (
            <div className="bg-rose-500/10 text-rose-500 border border-rose-500/20 px-3 py-1 rounded text-[10px] font-black uppercase tracking-widest animate-pulse">
              <i className="fas fa-exclamation-triangle mr-1"></i> Breaking
              Change Detected
            </div>
          )}
          <span className="text-slate-500 text-[10px] font-mono font-bold">
            Audit Progress ({progress}%)
          </span>
        </div>
        {isComplete && (
          <button
            onClick={copyToADO}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-[10px] font-bold uppercase tracking-widest rounded-lg transition-all shadow-lg shadow-indigo-600/10 flex items-center gap-2"
          >
            <i className="fas fa-file-export"></i> Copy Summary
          </button>
        )}
      </div>

      {/* Intelligence Reports - Only shown when complete */}
      {isComplete ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-in zoom-in-95 duration-500">
          <div className="bg-[#111113] border border-white/5 rounded-xl p-6 relative">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <i className="fas fa-sitemap text-indigo-400"></i> Architectural
              Impact
            </h3>
            <p className="text-sm text-slate-300 leading-relaxed italic">
              {analysis.architecturalImpact}
            </p>
          </div>
          <div className="bg-[#111113] border border-white/5 rounded-xl p-6">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <i className="fas fa-project-diagram text-violet-400"></i> System
              Alignment
            </h3>
            <p className="text-sm text-slate-300 leading-relaxed">
              {analysis.contextAlignment ||
                "Changes align with standard internal system configurations."}
            </p>
          </div>
        </div>
      ) : (
        <div className="bg-[#111113]/40 border border-dashed border-white/10 rounded-xl p-8 text-center">
          <p className="text-slate-600 text-[10px] font-bold uppercase tracking-[0.3em]">
            Full System Analysis Unlocks at 100%
          </p>
        </div>
      )}

      {/* Detailed Review */}
      <div className="space-y-4">
        <div className="flex items-center justify-between border-b border-white/5 pb-4 px-2">
          <h3 className="font-bold text-slate-100 uppercase text-xs tracking-[0.2em]">
            Detailed Findings
          </h3>
          <div className="flex bg-[#111113] border border-white/5 rounded-lg p-0.5">
            {["all", "high", "medium", "low"].map((id) => (
              <button
                key={id}
                onClick={() => setSeverityFilter(id as any)}
                className={`px-3 py-1 text-[9px] font-bold rounded uppercase transition-all ${
                  severityFilter === id
                    ? "bg-indigo-600 text-white shadow-lg"
                    : "text-slate-500 hover:text-slate-300"
                }`}
              >
                {id}{" "}
                <span className="opacity-50 ml-1">
                  {(counts as any)[id] ||
                    (analysis.codeReviewComments || []).length}
                </span>
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 gap-3">
          {filteredComments.map((comment, idx) => (
            <div
              key={idx}
              className="bg-[#111113] border border-white/5 rounded-xl overflow-hidden hover:border-white/10 transition-all group shadow-sm"
            >
              <div className="px-5 py-2.5 bg-white/[0.02] border-b border-white/5 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <SeverityBadge severity={comment.severity} />
                  <TypeBadge type={comment.type} />
                  <a
                    href={getADOLink(comment.file, comment.line)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[11px] font-mono text-indigo-400 truncate hover:text-indigo-300 transition-colors"
                  >
                    {comment.file}
                    {comment.line ? `:${comment.line}` : ""}
                  </a>
                </div>
              </div>
              <div className="p-5">
                <p className="text-slate-300 text-sm mb-4 leading-relaxed font-medium">
                  {comment.comment}
                </p>
                {comment.suggestedChange && (
                  <div className="bg-black border border-white/5 rounded-lg overflow-hidden group/code">
                    <div className="px-3 py-1 bg-white/5 border-b border-white/5 flex justify-between items-center">
                      <span className="text-[9px] font-bold text-emerald-500 uppercase tracking-[0.2em]">
                        Solution Patch
                      </span>
                      <button
                        onClick={() =>
                          navigator.clipboard.writeText(
                            comment.suggestedChange!
                          )
                        }
                        className="text-slate-500 hover:text-white transition-colors"
                      >
                        <i className="far fa-copy text-[10px]"></i>
                      </button>
                    </div>
                    <pre className="p-4 text-[11px] font-mono text-emerald-400 overflow-x-auto scrollbar-hide">
                      <code>{comment.suggestedChange}</code>
                    </pre>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>

        {processedCount < totalCount && (
          <div className="pt-10 flex flex-col items-center gap-4">
            <button
              onClick={onLoadNext}
              disabled={isAnalyzing}
              className="px-12 py-3.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 text-white rounded-lg font-bold text-xs uppercase tracking-widest shadow-xl shadow-indigo-600/10 transition-all active:scale-[0.98]"
            >
              {isAnalyzing ? (
                <>
                  <i className="fas fa-circle-notch fa-spin mr-2"></i>Diving
                  Deeper...
                </>
              ) : (
                "Continue Audit"
              )}
            </button>
            <p className="text-slate-600 text-[9px] font-bold uppercase tracking-[0.3em]">
              {totalCount - processedCount} files remaining
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
